CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION enforce_gig_band_matches_tour()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.tour_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1
      FROM tours
      WHERE id = NEW.tour_id
        AND band_id = NEW.band_id
    ) THEN
      RAISE EXCEPTION 'gigs.band_id must match tours.band_id for tour %', NEW.tour_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION enforce_profile_matches_user_type()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  expected_type text;
  actual_type text;
BEGIN
  expected_type := TG_ARGV[0];

  SELECT user_type INTO actual_type
  FROM users
  WHERE id = NEW.user_id;

  IF actual_type IS DISTINCT FROM expected_type THEN
    RAISE EXCEPTION 'user % has user_type %, expected % for this profile',
      NEW.user_id, actual_type, expected_type;
  END IF;

  IF expected_type = 'musician' AND EXISTS (
    SELECT 1 FROM band_profiles WHERE user_id = NEW.user_id
  ) THEN
    RAISE EXCEPTION 'user % already has a band profile', NEW.user_id;
  END IF;

  IF expected_type = 'band' AND EXISTS (
    SELECT 1 FROM musician_profiles WHERE user_id = NEW.user_id
  ) THEN
    RAISE EXCEPTION 'user % already has a musician profile', NEW.user_id;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email varchar(255) UNIQUE NOT NULL,
  password_hash varchar(255) NOT NULL,
  user_type varchar(20) NOT NULL
    CHECK (user_type IN ('musician', 'band', 'admin')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TABLE musician_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  stage_name varchar(150),
  bio text,
  base_city varchar(100) NOT NULL,
  base_country varchar(100) NOT NULL,
  has_passport boolean NOT NULL DEFAULT false,
  website_url varchar(255),
  video_reel_url varchar(255),
  hourly_rate_usd decimal(10, 2),
  is_available boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER musician_profiles_match_user_type
  BEFORE INSERT OR UPDATE OF user_id ON musician_profiles
  FOR EACH ROW
  EXECUTE FUNCTION enforce_profile_matches_user_type('musician');

CREATE TABLE band_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  band_name varchar(150) NOT NULL,
  genre varchar(100),
  bio text,
  website_url varchar(255),
  logo_url varchar(255),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER band_profiles_match_user_type
  BEFORE INSERT OR UPDATE OF user_id ON band_profiles
  FOR EACH ROW
  EXECUTE FUNCTION enforce_profile_matches_user_type('band');

CREATE TABLE instruments (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL
);

CREATE TABLE musician_instruments (
  musician_id uuid NOT NULL REFERENCES musician_profiles (id) ON DELETE CASCADE,
  instrument_id int NOT NULL REFERENCES instruments (id) ON DELETE RESTRICT,
  proficiency_level varchar(50) NOT NULL
    CHECK (proficiency_level IN ('beginner', 'intermediate', 'advanced', 'professional')),
  is_primary boolean NOT NULL DEFAULT false,
  PRIMARY KEY (musician_id, instrument_id)
);

CREATE INDEX musician_instruments_instrument_id_idx
  ON musician_instruments (instrument_id);

CREATE TABLE tours (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  band_id uuid NOT NULL REFERENCES band_profiles (id) ON DELETE CASCADE,
  title varchar(150) NOT NULL,
  description text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (end_date >= start_date)
);

CREATE INDEX tours_band_id_idx ON tours (band_id);

CREATE TABLE gigs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tour_id uuid REFERENCES tours (id) ON DELETE SET NULL,
  band_id uuid NOT NULL REFERENCES band_profiles (id) ON DELETE CASCADE,
  venue_name varchar(150) NOT NULL,
  city varchar(100) NOT NULL,
  country varchar(100) NOT NULL,
  gig_date date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER gigs_band_matches_tour
  BEFORE INSERT OR UPDATE OF tour_id, band_id ON gigs
  FOR EACH ROW
  EXECUTE FUNCTION enforce_gig_band_matches_tour();

CREATE INDEX gigs_band_id_idx ON gigs (band_id);
CREATE INDEX gigs_tour_id_idx ON gigs (tour_id);
CREATE INDEX gigs_gig_date_idx ON gigs (gig_date);

CREATE TABLE gig_listings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tour_id uuid REFERENCES tours (id) ON DELETE CASCADE,
  gig_id uuid REFERENCES gigs (id) ON DELETE CASCADE,
  instrument_needed int NOT NULL REFERENCES instruments (id) ON DELETE RESTRICT,
  pay_rate_usd decimal(10, 2) NOT NULL,
  pay_type varchar(50) NOT NULL
    CHECK (pay_type IN ('per_show', 'weekly_rate', 'flat_fee')),
  description text NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'filled', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (tour_id IS NOT NULL AND gig_id IS NULL)
    OR (tour_id IS NULL AND gig_id IS NOT NULL)
  )
);

CREATE TRIGGER gig_listings_set_updated_at
  BEFORE UPDATE ON gig_listings
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE INDEX gig_listings_tour_id_idx ON gig_listings (tour_id);
CREATE INDEX gig_listings_gig_id_idx ON gig_listings (gig_id);
CREATE INDEX gig_listings_instrument_needed_idx ON gig_listings (instrument_needed);
CREATE INDEX gig_listings_status_idx ON gig_listings (status);

CREATE TABLE applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  listing_id uuid NOT NULL REFERENCES gig_listings (id) ON DELETE CASCADE,
  musician_id uuid NOT NULL REFERENCES musician_profiles (id) ON DELETE CASCADE,
  pitch_message text,
  status varchar(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'reviewed', 'shortlisted', 'accepted', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (listing_id, musician_id)
);

CREATE TRIGGER applications_set_updated_at
  BEFORE UPDATE ON applications
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE INDEX applications_musician_id_idx ON applications (musician_id);
CREATE INDEX applications_status_idx ON applications (status);
